:sparkles: add parsing of query array values
mariusc23/express-query-boolean pull request #7
Opened 2017-10-26 15:11 UTC by jamesjnadeau

If you have query with the following structure: 
```
{
  stuff: [
    { thing: 'false' },
  ],
}
```
The current checks would not convert the value of `thing` to the booleon  false. 

This pull requests adds the ability to iterate over an Array and call parse on it's contents. 

I haven't looked at the tests for this project, but this is working for me locally. Will hopefully have time to update the test tomorrow.

2017-11-12 15:36 UTC, jamesjnadeau commented
Ok, added a test.

Also re-worked the logic a bit to separate it out and allow re-use for arrays. I ran found a bug where calling parse on an array item that was a string would cause that string to be be parsed incorrectly. Splitting the logic up allowed me to best reuse code again in this scenario. I also think it separates the concerns a bit and makes what is going on more clear.

2017-11-12 22:03 UTC, mariusc23 requested changes
Looks good! Thanks for taking the time to add tests. Can you just fix this typo ("fo" -> "of")? I'll merge and publish a new version when you're done.

2017-11-13 11:47 UTC, jamesjnadeau commented
ok, fixed my typo! Thanks @mariusc23

2018-02-21 14:44 UTC, JeSuisUnCaillou commented
Can this be merged into master now ? @mariusc23

2018-02-21 17:11 UTC, mariusc23 approved these changes

2018-02-21 17:11 UTC, merged

2018-02-21 17:15 UTC, mariusc23 commented
@JeSuisUnCaillou Published 2.0.0 with this PR. Thanks again for the PR @jamesjnadeau!